#!/usr/bin/env bash

# define current directory
export DIR=$(dirname $(readlink -f $0))

# load environment
source $DIR/../.env || exit;

# set local timezone or use UTC as default
sudo timedatectl set-timezone ${APP_TIMEZONE:-'UTC'};

# update
sudo apt-get update -y

# install php
sudo apt-get install -y php-fpm php-mysql php-mbstring php-xml
sudo cp -f $DIR/php.ini /etc/php/*/fpm/conf.d/.

# install composer
curl -sS 'https://getcomposer.org/installer' | php
sudo mv composer.phar /usr/bin/composer
echo -e 'export COMPOSER_HOME=~/.config/composer\n' >> $HOME/.profile
echo -e 'export PATH=$COMPOSER_HOME/vendor/bin:$PATH\n' >> $HOME/.profile

# install mysql
sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password $DB_USERNAME"
sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $DB_PASSWORD"
sudo apt-get install -qq mysql-server

# install nginx
sudo apt-get install -qq nginx-light
sudo cp -f $DIR/*.pem /etc/ssl/certs/.
sudo cp -f $DIR/*.key /etc/ssl/private/.
sudo chmod 777 /etc/ssl/private

# setup nginx
sudo rm -rf /var/www/html
sudo unlink /etc/nginx/sites-enabled/*
sudo cp -f $DIR/nginx.conf /etc/nginx/sites-enabled/.

# setup database
mysql -u$DB_USERNAME -p$DB_PASSWORD -e "DROP DATABASE IF EXISTS \`$DB_DATABASE\`"
mysql -u$DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE \`$DB_DATABASE\` CHARACTER SET utf8"

# restart services
sudo systemctl restart nginx
sudo systemctl restart mysql
